server:
  port: 8089

spring:
  application:
    name: Data Service
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true  
  datasource:
    url: jdbc:mysql://localhost:3306/i_budget
    username: root
    password: admin@root
    driver-class-name: com.mysql.cj.jdbc.Driver    
  profiles:
    active: 'dev'
  liquibase:
    change-log: classpath:config/liquibase/master.xml